# Generated by Django 4.1.1 on 2022-09-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('tel', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
