# Generated by Django 4.1.1 on 2022-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=60)),
                ('guest_email', models.EmailField(max_length=255, unique=True)),
                ('guest_address', models.TextField(max_length=255, null=True)),
                ('guest_tel', models.CharField(max_length=10)),
                ('guest_pwd', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
