# Generated by Django 4.1.1 on 2022-09-24 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='type_id',
            new_name='type',
        ),
    ]
