# Generated by Django 4.1.1 on 2022-09-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_guest_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='id',
            new_name='guest_id',
        ),
    ]
