# Generated by Django 4.1.1 on 2022-09-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'ชาย'), (2, 'หญิง')]),
        ),
    ]
