# Generated by Django 4.1.1 on 2022-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_customer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
