# Generated by Django 4.1.1 on 2022-09-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_rooms_price_booking_status_roomtype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.DateField(),
        ),
    ]
