# Generated by Django 4.1.1 on 2022-09-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_roomtype_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
