# Generated by Django 4.1.1 on 2022-10-07 23:21

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_roomtype_limit_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cust',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_code',
            field=creditcards.models.CardNumberField(max_length=25, null=True, verbose_name='security code'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_expiry',
            field=creditcards.models.CardExpiryField(null=True, verbose_name='expiration date'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_number',
            field=creditcards.models.CardNumberField(max_length=25, null=True, verbose_name='card number'),
        ),
    ]
