# Generated by Django 4.1.1 on 2022-10-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_remove_payment_amount_remove_payment_cust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_amount',
            field=models.IntegerField(default=10000),
        ),
    ]
