# Generated by Django 4.1.1 on 2022-10-07 23:38

import creditcards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_payment_pay_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_code',
            field=creditcards.models.CardNumberField(max_length=3, null=True, verbose_name='security code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_expiry',
            field=creditcards.models.CardExpiryField(max_length=4, null=True, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_number',
            field=creditcards.models.CardNumberField(max_length=16, null=True, verbose_name='card number'),
        ),
    ]
