# Generated by Django 4.1.1 on 2022-10-08 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_alter_multiimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='upload/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
