# Generated by Django 4.1.1 on 2022-10-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_alter_multiimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimage',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/images/'),
        ),
    ]
