# Generated by Django 4.1.1 on 2022-10-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_alter_multiimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='bed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
