# Generated by Django 4.1.1 on 2022-10-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_roomtype_bed_alter_roomtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
