# Generated by Django 4.1.1 on 2022-10-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_alter_roomtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pay',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.payment'),
        ),
    ]
