# Generated by Django 4.1.1 on 2022-10-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_alter_transaction_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.booking'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.payment'),
        ),
    ]
