# Generated by Django 4.1.1 on 2022-10-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_alter_transaction_booking_alter_transaction_cust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.roomtype'),
        ),
    ]
