# Generated by Django 4.1.1 on 2022-10-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_remove_transaction_booking_remove_transaction_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.transaction'),
        ),
    ]
